---
title: "Anxiety Identity & Coping Analysis"
output: html_document
---

```{r, echo = F}
# R version 4.1.2
library(tidyverse) #2.0.0
library(here) #1.0.1
library(brms) #2.20.4
library(psych) #2.3.9

load(here("anlys_df.RData"))

set.seed(6680142)

df <- anlys_df %>%
  # Select and rename variables for analysis
  select(
    anxiety_identity = anxiety_identity_rev,
    symptom_severity = oa_sx_sev_m_std,
    situational_avoidance = avo,
    experiential_avoidance = comp_act_willing,
    anxiety_duration
  ) %>%
  mutate(
    # Recode anxiety identity to start at 1, per pre-registration
    anxiety_identity = anxiety_identity + 1,
    # Recode situational avoidance to start at 1, per pre-registration
    situational_avoidance = situational_avoidance + 1,
    # Recode anxiety duration to start at 1, per manuscript
    anxiety_duration = anxiety_duration + 1,
    # Reverse-code experiential avoidance such that higher values = more avoidance
    experiential_avoidance = 8 - experiential_avoidance,
    # Create symptom severity groups for plotting
    symptom_severity_group = cut(symptom_severity, c(-9, -1, 1, 9)),
    # Create ordered factor versions of DVs for regressions
    situational_avoidance_fct = factor(situational_avoidance, ordered = T),
    experiential_avoidance_fct = factor(experiential_avoidance, ordered = T)
  )
```

## Descriptive Statistis

```{r}
numeric_variables <- c(
  "anxiety_identity", 
  "situational_avoidance",
  "experiential_avoidance",
  "symptom_severity",
  "anxiety_duration"
)

# Histograms
for(x in numeric_variables) hist(df[[x]])

# Correlations
correlations <- df %>%
  select(all_of(numeric_variables)) %>%
  corr.test(method = "spearman", use = "pairwise.complete.obs")

round(correlations$r, 2)
round(correlations$p, 3)
```

## Regressions

### Situational Avoidance

```{r}
# model_ba <- brm(
#   data = df, 
#   formula = situational_avoidance_fct ~ mo(anxiety_identity), 
#   family = cumulative("probit")
# )
# saveRDS(model_ba, here("models", "model_ba.rds"))
model_ba <- readRDS(here("models", "model_ba.rds"))
summary(model_ba)
pp_check(model_ba)

# model_ba_control <- brm(
#   data = df, 
#   formula = situational_avoidance_fct ~ mo(anxiety_identity) + symptom_severity,
#   family = cumulative("probit")
# )
# saveRDS(model_ba_control, here("models", "model_ba_control.rds"))
model_ba_control <- readRDS(here("models", "model_ba_control.rds"))
summary(model_ba_control)
pp_check(model_ba_control)

# model_ba_severity_mod <- brm(
#   data = df, 
#   formula = situational_avoidance_fct ~ mo(anxiety_identity)*symptom_severity, 
#   family = cumulative("probit")
# )
# saveRDS(model_ba_severity_mod, here("models", "model_ba_severity_mod.rds"))
model_ba_severity_mod <- readRDS(here("models", "model_ba_severity_mod.rds"))
summary(model_ba_severity_mod)
pp_check(model_ba_severity_mod)

# model_ba_duration_mod <- brm(
#   data = df, 
#   formula = situational_avoidance_fct ~ mo(anxiety_identity)*mo(anxiety_duration) + symptom_severity, 
#   family = cumulative("probit")
# )
# saveRDS(model_ba_duration_mod, here("models", "model_ba_duration_mod.rds"))
model_ba_duration_mod <- readRDS(here("models", "model_ba_duration_mod.rds"))
summary(model_ba_duration_mod)
pp_check(model_ba_duration_mod)
```

### Experiential Avoidance

```{r}
# model_ea <- brm(
#   data = df, 
#   formula = experiential_avoidance_fct ~ mo(anxiety_identity), 
#   family = cumulative("probit")
# )
# saveRDS(model_ea, here("models", "model_ea.rds"))
model_ea <- readRDS(here("models", "model_ea.rds"))
summary(model_ea)
pp_check(model_ea)

# model_ea_control <- brm(
#   data = df, 
#   formula = experiential_avoidance_fct ~ mo(anxiety_identity) + symptom_severity,
#   family = cumulative("probit")
# )
# saveRDS(model_ea_control, here("models", "model_ea_control.rds"))
model_ea_control <- readRDS(here("models", "model_ea_control.rds"))
summary(model_ea_control)
pp_check(model_ea_control)

# model_ea_severity_mod <- brm(
#   data = df, 
#   formula = experiential_avoidance_fct ~ mo(anxiety_identity)*symptom_severity, 
#   family = cumulative("probit")
# )
# saveRDS(model_ea_severity_mod, here("models", "model_ea_severity_mod.rds"))
model_ea_severity_mod <- readRDS(here("models", "model_ea_severity_mod.rds"))
summary(model_ea_severity_mod)
pp_check(model_ea_severity_mod)

# model_ea_duration_mod <- brm(
#   data = df, 
#   formula = experiential_avoidance_fct ~ mo(anxiety_identity)*mo(anxiety_duration) + symptom_severity, 
#   family = cumulative("probit")
# )
# saveRDS(model_ea_duration_mod, here("models", "model_ea_duration_mod.rds"))
model_ea_duration_mod <- readRDS(here("models", "model_ea_duration_mod.rds"))
summary(model_ea_duration_mod)
pp_check(model_ea_duration_mod)
```

### Combined, for comparison:

```{r}
# Estimate both DVs simultaneously, to compare posterior distributions of estimates
# model_mv_control <- brm(
#   data = df,
#   formula = mvbind(experiential_avoidance_fct, situational_avoidance_fct) ~ mo(anxiety_identity) + symptom_severity,
#   family = cumulative("probit")
# )
# saveRDS(model_mv_control, here("models", "model_mv_control.rds"))
model_mv_control <- readRDS(here("models", "model_mv_control.rds"))

# Compare posterior distributions of effect estimates
posterior_draws <- model_mv_control %>%
  as_draws_df() %>%
  mutate(difference = bsp_situationalavoidancefct_moanxiety_identity - bsp_experientialavoidancefct_moanxiety_identity)

posterior_draws %>%
  summarize(
    sa_mean = mean(bsp_situationalavoidancefct_moanxiety_identity),
    ea_mean = mean(bsp_experientialavoidancefct_moanxiety_identity),
    diff_mean = mean(difference),
    pos_diff_prop = mean(difference > 0)
  )

# Visualize difference
posterior_draws %>%
  ggplot(aes(x = difference)) +
  geom_density(fill = "skyblue", alpha = 0.5) +
  geom_vline(xintercept = 0, linetype = "dashed")

# Formal test of difference (same as above but provides CI)
test_diff <- hypothesis(
  model_mv_control,
  "bsp_situationalavoidancefct_moanxiety_identity = bsp_experientialavoidancefct_moanxiety_identity",
  class = NULL
)
```

## Figures

### Raw Data

```{r}
df %>%
  pivot_longer(c(situational_avoidance, experiential_avoidance)) %>%
  mutate(
    # Rename variables
    name = recode_factor(
      name,
      "situational_avoidance" = "Situational Avoidance",
      "experiential_avoidance" = "Experiential Avoidance"
    ),
    # Remove points where no SE can be calculated
    value = case_when(
      name == "Situational Avoidance" & anxiety_identity == 1 & value == 1 ~ NA,
      name == "Situational Avoidance" & anxiety_identity == 2 & value == 5 ~ NA,
      name == "Experiential Avoidance" & anxiety_identity == 1 & value == 1 ~ NA,
      name == "Experiential Avoidance" & anxiety_identity == 2 & value == 7 ~ NA,
      T ~ value
    )
  ) %>%
  ggplot(aes(anxiety_identity, value, group = symptom_severity_group, linetype = symptom_severity_group, color = symptom_severity_group)) +
  stat_summary(alpha = .25) +
  geom_smooth(method = "lm", formula = "y ~ x", se = F) +
  facet_wrap(~ name, scales = "free") +
  scale_x_continuous(name = "Anxiety Identity Centrality") +
  scale_color_manual(
    name = "Anxiety Symptom Severity",
    labels = c("1 SD or More Below Mean", "Within 1 SD of Mean", "1 SD or More Above Mean"),
    values = c("#56B4E9", "#E69F00", "#009E73"),
    guide = guide_legend(reverse = T)
  ) +
  scale_linetype_manual(
    name = "Anxiety Symptom Severity",
    labels = c("1 SD or More Below Mean", "Within 1 SD of Mean", "1 SD or More Above Mean"),
    values = c(4, 2, 1),
    guide = guide_legend(reverse = T)
  ) +
  ggh4x::facetted_pos_scales(y = list(name == "Situational Avoidance" ~ scale_y_continuous(name = "Avoidance", limits = c(1, 5)),
                                      name == "Experiential Avoidance" ~ scale_y_continuous(name = "Avoidance", limits = c(1, 7), breaks = 1:7))) +
  theme_classic()

ggsave(filename = here("figures", "Avoidance by Identity - Raw Data.png"),
       width = 8,
       height = 4,
       units = "in",
       dpi = 1200)
```

### Model Data

```{r}
# Calculate marginal effects; rather than use conditional_effects() plot, extract
# plot data and create the plot manually
plot_data_ba <- conditional_effects(
  model_ba_control,
  effects = "anxiety_identity",
  method = "posterior_linpred",
  condition = data.frame(symptom_severity = 0),
  robust = F
) %>%
  pluck("anxiety_identity")

plot_data_ea <- conditional_effects(
  model_ea_control,
  effects = "anxiety_identity",
  method = "posterior_linpred",
  condition = data.frame(symptom_severity = 0),
  robust = F
) %>%
  pluck("anxiety_identity")

plot_data_combined <- bind_rows(
  lst(
    plot_data_ba,
    plot_data_ea
  ),
  .id = "model"
)

plot_data_cleaned <- plot_data_combined %>%
  mutate(
    dv = case_match(
      model,
      "plot_data_ba" ~ "Situational Avoidance",
      "plot_data_ea" ~ "Experiential Avoidance"
    ) %>%
      factor(levels = c("Situational Avoidance", "Experiential Avoidance"))
  ) %>%
  select(
    dv, anxiety_identity, estimate__, lower__, upper__
  )

plot_data_cleaned %>%
  ggplot(aes(anxiety_identity, estimate__)) +
  geom_line(size = 1) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__), alpha = .1) +
  scale_x_continuous(name = "Anxiety Identity Centrality") +
  scale_y_continuous(name = "Avoidanct Coping (SD Units)") +
  facet_wrap(~ dv) +
  theme_classic()

ggsave(filename = here("figures", "Avoidance by Identity - Model Data.png"),
       width = 6,
       height = 3,
       units = "in",
       dpi = 1200)
```

```{r}
# Effects broken down by symptom severity (not used)
plot_data_ba <- conditional_effects(
  model_ba_control,
  effects = "anxiety_identity",
  conditions = data.frame(
    symptom_severity = c(-1, 0, 1)
  ),
  method = "posterior_linpred"
) %>%
  pluck("anxiety_identity")

plot_data_ba %>%
  mutate(
    symptom_severity = case_match(
      symptom_severity,
      -1 ~ "Low Symptom Severity (-1 S.D.)",
      0 ~ "Mean Symptom Severity",
      1 ~ "High Symptom Severity (+1 S.D.)"
    ) %>%
      factor(levels = c("Low Symptom Severity (-1 S.D.)", "Mean Symptom Severity", "High Symptom Severity (+1 S.D.)"))
  ) %>%
  ggplot(aes(anxiety_identity, estimate__)) +
  geom_line(size = 1) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__), alpha = .1) +
  scale_x_continuous(name = "Anxiety Identity Centrality") +
  scale_y_continuous(name = "Situational Avoidance (S.D. Units)") +
  facet_wrap(~ symptom_severity) +
  theme_classic()
```
